/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/books': {
    post: operations['BooksController_create'];
    get: operations['BooksController_findAll'];
  };
  '/books/{id}': {
    get: operations['BooksController_findOne'];
    put: operations['BooksController_update'];
    delete: operations['BooksController_remove'];
  };
  '/categories': {
    get: operations['CategoriesController_findAll'];
  };
  '/categories/{id}': {
    get: operations['CategoriesController_findOne'];
  };
}

export interface operations {
  BooksController_create: {
    parameters: {};
    requestBody: {
      'application/json': components['schemas']['CreateBookDto'];
    };
    responses: {
      /** The record has been successfully created. */
      201: unknown;
    };
  };
  BooksController_findAll: {
    parameters: {};
    responses: {
      200: {
        'application/json': components['schemas']['BookDto'][];
      };
    };
  };
  BooksController_findOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        'application/json': components['schemas']['BookDto'];
      };
    };
  };
  BooksController_update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      'application/json': components['schemas']['BookDto'];
    };
    responses: {
      200: {
        'application/json': { [key: string]: any };
      };
    };
  };
  BooksController_remove: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        'application/json': { [key: string]: any };
      };
    };
  };
  CategoriesController_findAll: {
    parameters: {};
    responses: {
      200: {
        'application/json': components['schemas']['CategoryDto'][];
      };
    };
  };
  CategoriesController_findOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        'application/json': components['schemas']['CategoryDto'];
      };
    };
  };
}

export interface components {
  schemas: {
    CreateBookDto: {
      title: string;
      authorId: number;
      linkToRead: string;
    };
    BookDto: {
      title: string;
      description?: string;
      authorId: number;
      publishedDate?: string;
      categoryId?: number;
      averageRating?: number;
      ratingsCount?: number;
      thumbnail?: string;
      language?: string;
      linkToRead: string;
      isPublic: boolean;
    };
    CategoryDto: {
      title: string;
      books: { [key: string]: any }[];
    };
  };
}
